import type { Player } from "@/types/player";

export const mockPlayers: Player[] = [
  { id: "p1", name: "محمد الفكي", photo: "/players/placeholder.svg", preferredPosition: "MID" },
  { id: "p2", name: "الطيب", photo: "/players/placeholder.svg", preferredPosition: "DEF" },
  { id: "p3", name: "ايمن قباني", photo: "/players/placeholder.svg", preferredPosition: "DEF" },
  { id: "p4", name: "محمد عثمان", photo: "/players/placeholder.svg", preferredPosition: "ATT" },
  { id: "p5", name: "عمر جعفر", photo: "/players/placeholder.svg", preferredPosition: "MID" },
  { id: "p6", name: "هاني", photo: "/players/placeholder.svg", preferredPosition: "MID" },
  { id: "p7", name: "الواثق", photo: "/players/placeholder.svg", preferredPosition: "ATT" },
  { id: "p8", name: "سامي", photo: "/players/placeholder.svg", preferredPosition: "ATT" },
  { id: "p9", name: "الطاهر", photo: "/players/placeholder.svg", preferredPosition: "ATT" },
  { id: "p10", name: "عماد مبارك", photo: "/players/placeholder.svg", preferredPosition: "DEF" },
  { id: "p11", name: "معاذ الأزرق", photo: "/players/placeholder.svg", preferredPosition: "MID" },
  { id: "p12", name: "احمد فضل", photo: "/players/placeholder.svg", preferredPosition: "MID" },
  { id: "p13", name: "امين مبارك", photo: "/players/placeholder.svg", preferredPosition: "MID" },
  { id: "p14", name: "امين عيسى", photo: "/players/placeholder.svg", preferredPosition: "MID" },
  { id: "p15", name: "عبدالله", photo: "/players/placeholder.svg", preferredPosition: "DEF" },
  { id: "p16", name: "علاء الدين", photo: "/players/placeholder.svg", preferredPosition: "DEF" },
  { id: "p17", name: "شادي", photo: "/players/placeholder.svg", preferredPosition: "ATT" },
  { id: "p18", name: "هيثم", photo: "/players/placeholder.svg", preferredPosition: "ATT" },
  { id: "p19", name: "أيمن احمد", photo: "/players/placeholder.svg", preferredPosition: "ATT" },
  { id: "p20", name: "حذيفة احمد", photo: "/players/placeholder.svg", preferredPosition: "DEF" },
  { id: "p21", name: "محمد بشير", photo: "/players/placeholder.svg", preferredPosition: "MID" },
  { id: "p22", name: "صديق هباني", photo: "/players/placeholder.svg", preferredPosition: "MID" },
];
